import { Navbar } from '@/components/Navbar';
import { Footer } from '@/components/Footer';
import { Button } from '@/components/ui/button';
import { Video, ArrowRight, Music, Subtitles, Zap, Clapperboard, Wand2 } from 'lucide-react';
import Image from 'next/image';

export default function ReelMakerPage() {
  return (
    <main className="min-h-screen bg-white selection:bg-primary/30 selection:text-white">
      <Navbar />
      
      {/* Hero Section */}
      <section className="pt-32 pb-16 lg:pt-40 lg:pb-32 overflow-hidden relative min-h-[500px] lg:min-h-[600px] flex items-center">
        <div className="absolute top-0 left-0 w-full h-full bg-gradient-to-br from-pink-50/60 via-transparent to-violet-50/60 pointer-events-none" />
        
        {/* Full-bleed right image (Desktop) */}
        <div className="absolute top-0 right-0 w-full lg:w-[60%] h-full z-0 hidden lg:block">
          {/* Gradient to smooth out the left edge of the image */}
          <div className="absolute inset-0 bg-gradient-to-r from-white via-white/50 to-transparent z-10 w-[30%]" />
          <img 
            src="/images/about-reels.jpg" 
            alt="AI Reel Maker in action" 
            className="w-full h-full object-cover object-[center_top] [mask-image:linear-gradient(to_right,transparent_0%,black_15%,black_100%)]"
          />
        </div>

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10 w-full">
          <div className="flex flex-col lg:flex-row items-center justify-between gap-12 lg:gap-8">
            
            {/* Left Content */}
            <div className="w-full lg:w-[45%] flex flex-col items-start py-10 lg:py-20">
              <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-white shadow-sm border border-slate-100 mb-6">
                <Video className="w-4 h-4 text-pink-500" />
                <span className="text-sm font-semibold text-transparent bg-clip-text bg-gradient-to-r from-pink-500 to-violet-500">
                  Viral Video Creation
                </span>
              </div>
              
              <h1 className="text-5xl md:text-6xl lg:text-[72px] font-bold text-slate-900 mb-6 tracking-tight leading-[1.1]">
                AI Reel Maker
              </h1>
              
              <p className="text-xl md:text-[22px] text-slate-600 leading-relaxed max-w-lg font-medium mb-8">
                Turn ideas into viral Instagram Reels and YouTube Shorts in minutes. Auto-captions, trending audio, and stunning visuals—all generated by AI.
              </p>
              
              <Button variant="default" size="lg" className="h-14 px-8 text-base shadow-lg shadow-pink-500/25 group font-semibold rounded-full bg-gradient-to-r from-pink-600 to-violet-500 hover:from-pink-700 hover:to-violet-600 border-0">
                <span className="flex items-center gap-2 text-white">
                  Create Your First Reel
                </span>
                <ArrowRight className="w-4 h-4 ml-2 group-hover:translate-x-1 transition-transform text-white" />
              </Button>
            </div>
            
            {/* Mobile Image (hidden on desktop) */}
            <div className="w-full relative lg:hidden">
              <div className="relative w-full aspect-[4/3] overflow-hidden rounded-3xl shadow-2xl">
                <img 
                  src="/images/about-reels.jpg" 
                  alt="AI Reel Maker in action" 
                  className="w-full h-full object-cover object-center"
                />
              </div>
            </div>

          </div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="py-16 border-y border-slate-100 bg-white relative z-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-10 md:gap-8 divide-x-0 md:divide-x divide-slate-100 text-center">
            <div className="flex flex-col items-center justify-center">
              <h3 className="text-4xl md:text-5xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-pink-600 to-violet-500 mb-3 tracking-tight">2M+</h3>
              <p className="text-[13px] font-bold text-slate-500 uppercase tracking-wider">Reels Created</p>
            </div>
            <div className="flex flex-col items-center justify-center">
              <h3 className="text-4xl md:text-5xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-pink-600 to-violet-500 mb-3 tracking-tight">3x</h3>
              <p className="text-[13px] font-bold text-slate-500 uppercase tracking-wider">More Views</p>
            </div>
            <div className="flex flex-col items-center justify-center">
              <h3 className="text-4xl md:text-5xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-pink-600 to-violet-500 mb-3 tracking-tight">Auto</h3>
              <p className="text-[13px] font-bold text-slate-500 uppercase tracking-wider">Subtitles & Edits</p>
            </div>
            <div className="flex flex-col items-center justify-center">
              <h3 className="text-4xl md:text-5xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-pink-600 to-violet-500 mb-3 tracking-tight">100%</h3>
              <p className="text-[13px] font-bold text-slate-500 uppercase tracking-wider">Copyright Safe</p>
            </div>
          </div>
        </div>
      </section>

      {/* How it Works Section */}
      <section className="py-24 lg:py-32 bg-[#fafbfc]">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold text-slate-900 tracking-tight mb-4">
              How AI Reel Maker Works
            </h2>
            <p className="text-slate-500 text-lg max-w-2xl mx-auto font-medium">
              Produce engaging, scroll-stopping videos without ever touching a timeline.
            </p>
          </div>
          
          <div className="flex flex-col lg:flex-row items-center gap-16 lg:gap-24">
            
            {/* Left Image with Video Generation Animation */}
            <div className="w-full lg:w-1/2">
              <div className="relative w-full aspect-[9/16] md:aspect-[3/4] rounded-[32px] overflow-hidden shadow-2xl group max-w-md mx-auto">
                <img 
                  src="/images/about-campaigns.jpg" 
                  alt="Video creation process" 
                  className="w-full h-full object-cover"
                />
                
                <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent" />
                <div className="absolute bottom-8 left-6 right-6">
                  <div className="bg-white/95 backdrop-blur p-4 rounded-xl shadow-lg border border-white/20">
                    <div className="flex items-center justify-between mb-3">
                      <div className="flex items-center gap-3">
                        <div className="w-8 h-8 rounded-full bg-pink-100 flex items-center justify-center">
                          <Wand2 className="w-4 h-4 text-pink-600" />
                        </div>
                        <span className="font-semibold text-slate-900 text-sm">Rendering Video...</span>
                      </div>
                      <span className="text-xs font-bold text-pink-600">84%</span>
                    </div>
                    
                    {/* Animated Progress Bar */}
                    <div className="w-full bg-slate-100 h-2 rounded-full overflow-hidden">
                      <div 
                        className="bg-gradient-to-r from-pink-500 to-violet-500 h-full rounded-full" 
                        style={{
                          animation: "renderProgress 3s ease-in-out infinite"
                        }}
                      />
                    </div>
                  </div>
                </div>
                
                <style>{`
                  @keyframes renderProgress {
                    0% { width: 0%; }
                    70% { width: 84%; }
                    100% { width: 100%; }
                  }
                `}</style>
              </div>
            </div>
            
            {/* Right Content Steps */}
            <div className="w-full lg:w-1/2 flex flex-col space-y-10">
              
              <div className="flex gap-6">
                <div className="flex-shrink-0 w-14 h-14 rounded-2xl bg-pink-100 flex items-center justify-center shadow-sm">
                  <span className="text-xl font-bold text-pink-600">1</span>
                </div>
                <div>
                  <h3 className="text-2xl font-bold text-slate-900 mb-2">Write or Generate Script</h3>
                  <p className="text-slate-600 font-medium leading-relaxed">
                    Provide a topic, URL, or idea. Our AI will write a highly engaging script designed specifically to retain viewer attention.
                  </p>
                </div>
              </div>

              <div className="flex gap-6">
                <div className="flex-shrink-0 w-14 h-14 rounded-2xl bg-violet-100 flex items-center justify-center shadow-sm">
                  <span className="text-xl font-bold text-violet-600">2</span>
                </div>
                <div>
                  <h3 className="text-2xl font-bold text-slate-900 mb-2">AI Assembles the Video</h3>
                  <p className="text-slate-600 font-medium leading-relaxed">
                    AI automatically selects premium stock footage, matches scene transitions, and adds dynamic text overlays to keep viewers hooked.
                  </p>
                </div>
              </div>

              <div className="flex gap-6">
                <div className="flex-shrink-0 w-14 h-14 rounded-2xl bg-fuchsia-100 flex items-center justify-center shadow-sm">
                  <span className="text-xl font-bold text-fuchsia-600">3</span>
                </div>
                <div>
                  <h3 className="text-2xl font-bold text-slate-900 mb-2">Sync Audio & Post</h3>
                  <p className="text-slate-600 font-medium leading-relaxed">
                    We'll add a hyper-realistic AI voiceover, perfectly sync background music, and let you export or auto-publish directly to Instagram, YouTube, and TikTok.
                  </p>
                </div>
              </div>

            </div>
            
          </div>
        </div>
      </section>

      {/* Reel Maker Features Section */}
      <section className="py-24 bg-[#090b14] relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-b from-[#090b14] to-[#111111]" />
        
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold text-white tracking-tight mb-4">
              Everything you need for viral growth
            </h2>
            <p className="text-slate-400 text-lg max-w-2xl mx-auto font-medium">
              We took the most effective video marketing strategies and automated them into one powerful tool.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {[
              {
                title: "Dynamic Auto-Captions",
                desc: "Get those trendy, word-by-word animated captions automatically. Proven to increase watch time by up to 40%.",
                icon: <Subtitles className="w-6 h-6 text-[#fc9a5d]" />
              },
              {
                title: "AI Voiceovers",
                desc: "Choose from hundreds of ultra-realistic voices across 50+ languages, including Hindi and Indian regional accents.",
                icon: <Music className="w-6 h-6 text-[#f0449b]" />
              },
              {
                title: "Trendy Templates",
                desc: "Don't guess what works. Use templates based on the most viral formats currently trending on Reels and TikTok.",
                icon: <Clapperboard className="w-6 h-6 text-[#be32ff]" />
              },
              {
                title: "Text to Video",
                desc: "Turn your blog posts, product pages, or long-form videos into bite-sized engaging clips instantly.",
                icon: <Video className="w-6 h-6 text-blue-400" />
              },
              {
                title: "Smart Trimming",
                desc: "AI identifies the most exciting hooks and moments in your long videos to create perfect 15-60 second clips.",
                icon: <Zap className="w-6 h-6 text-emerald-400" />
              },
              {
                title: "B-Roll Magic",
                desc: "AI automatically pulls relevant B-roll footage and images when you talk, keeping the visuals constantly moving.",
                icon: <Wand2 className="w-6 h-6 text-pink-400" />
              }
            ].map((feature, idx) => (
              <div key={idx} className="bg-white/5 border border-white/10 rounded-3xl p-8 hover:bg-white/10 transition-colors group cursor-pointer">
                <div className="w-12 h-12 rounded-2xl bg-white/5 flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
                  {feature.icon}
                </div>
                <h3 className="text-xl font-bold text-white mb-3 tracking-tight">{feature.title}</h3>
                <p className="text-slate-400 leading-relaxed text-sm font-medium">
                  {feature.desc}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>
      
      {/* CTA Section */}
      <section className="py-24 bg-white relative">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="bg-gradient-to-br from-pink-600 to-violet-600 rounded-[40px] p-12 md:p-16 text-center relative overflow-hidden shadow-2xl">
            <div className="absolute top-0 right-0 w-64 h-64 bg-white/10 blur-[100px] rounded-full pointer-events-none -translate-y-1/2 translate-x-1/2" />
            <div className="absolute bottom-0 left-0 w-64 h-64 bg-white/10 blur-[100px] rounded-full pointer-events-none translate-y-1/2 -translate-x-1/2" />
            
            <h2 className="text-3xl md:text-5xl font-bold text-white mb-6 relative z-10 tracking-tight">
              Ready to go viral?
            </h2>
            <p className="text-white/90 text-lg md:text-xl max-w-2xl mx-auto mb-10 relative z-10 font-medium">
              Start creating professional short-form videos in minutes, not hours. Drive massive traffic with DhandaGrow's AI Reel Maker.
            </p>
            <Button variant="secondary" size="lg" className="relative z-10 h-14 px-10 text-lg font-bold rounded-full text-pink-700 bg-white hover:bg-slate-50 border-0 shadow-xl">
              Create Free Video
            </Button>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  );
}
